name: Docker Release
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: phlienert/hello-world-docker-action@latest
        with:
          who-to-greet: '@phlienert'
