name: Docker Release
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: phlienert/hello-world-docker-action@v2
        with:
          who-to-greet: '@phlienert'
